### ISSUE TITLE
Questions about LDAK-GBAT

### ISSUE THREAD

**Issue by zqsha** [takiy-berrandou/LDAK-GBAT-paper-scripts#1]
Hi there,
Thanks for developing such an amazing toolbox. I have a question about this toolbox. First, I used the following command lines to run an analysis.

# step1: Divide predictors into genes:
./ldak5.2.linux \
--cut-genes asd \
--genefile GRCh37_ensembl_GENES.loc \
--gene-buffer 50000 \
--bfile g1000_nonFin_eur_imp_chr_1_22_posid_common_snps

# step2: Test each gene for association
./ldak5.2.linux \
--calc-genes-reml asd \
--summary test.txt \
--bfile g1000_nonFin_eur_imp_chr_1_22_posid_common_snps \
--ignore-weights YES \
--power -0.25

Q1: Is the bifle used in step1 and step2 supposed to be the same?
Q2: For example, I run the gene-based analysis using previously published autism GWAS summary statistics. Given that the predictors specified in --summary are coded as Chr:Pos, we also need to use the same format in bfiles, i.e. present SNP ID with Chr:Pos. Right?
Q3: For bfiles in the first step, we must combine all of the chromosomes together to generate a single cross-chromosome bfiles, rather than bfiles per chromosome. Right? If yes, that means if I wanted to use genotype data of 10000 subjects from UKB dataset, I have to combine the genotype data across all chromosomes together. Right? Is yes, I think it's a bit heavy computation, so I would prefer to use the genotype data from 404 non-Fin Europeans.
Q4:  For the bfiles in step1, in the manual, it mentioned, "you will require a (**well-matched**) reference panel. Ideally, this should contain at least 2000 samples (otherwise, Reference Panel provides scripts for constructing a smaller panel from 1000 Genome Project data)." Given that the GWAS summary statistics are calculated from EUR, there are only 404 non-Fin Europeans in 1000 Genome Project, which can be downloaded from https://genetics.ghpc.au.dk/doug/1000g.tar.gz. If I use the bfiles that contain genotype data from these 404 non-Fin Europeans in Step1 and Step2, do you think it makes sense? 

Thanks,

**Comment by takiy-berrandou** [comment]
Hi
Thanks for your interest.
Your command lines seem correct. here below some answer to your questions.
A1: Yes, the bfile used in both steps 1 and 2 supposed to be the same. in step1 is used to annotate SNPs to genes according to annotation file. in Step2 the bfile of reference panel is used to calculate the SNP-SNP correlation needed for the set-SNP association analysis.
A2: Yes, both summary statistics and reference panel (bfile) need to use same variants ID (e.g., Chr:Pos)
A3: in theory, we can run analysis by chromosome. However our recommendation is to use all chromosomes to have acurate gene association  p-values (LRT_P_Perm in the result output) based on permutation procedure (see paper for details). 
In practice, constructing a reference panel using 10k individuals from UKBB should not be computationally too heavy. In our case we constructed the 10k individuals UKBB reference panel (size: 19 Gb in plink format) using commands from plink2 and LDAK
```
for i in $(seq 1 22)
do
plink2 --pfile /biobank/geno_plink/chr$i --set-all-var-ids '@:#' --make-pgen --out temp_chr$i --threads 4
plink2 --pfile temp_chr$i --extract list_snps_posid_to_analyse.txt --keep list_indiv_to_keep.txt --make-bed --out ukbb_imp_common_chr$i --threads 4
done
rm temp*
        
for j in {1..22}; do echo ukbb_imp_common_chr$j >> list.txt; done
 ldak5.2.linux --mbfile list.txt --quick-merge YES --make-bed ukbb_imp_common_all_chr
```
This been said using a smaller reference panel such as the 404 non-FIN Eur individuals from 1000G project should be ok.

A4: Yes, using other reference panel such as the 404 non-Fin Europeans or individuals from in house data if access to individual level genotyping data is ok too. The only impact when using a small reference panel should be a small false positive inflation as showed in the paper results.

**Comment by zqsha** [comment]
Thanks for your suggestions. I have another question. When I run the step2: Test each gene for association with the following command line,
./ldak5.2.linux \
--calc-genes-reml asd \
--summary test.txt \
--bfile g1000_nonFin_eur_imp_chr_1_22_posid_common_snps \
--ignore-weights YES \
--power -0.25 \
--extract asd/genes.predictors

where "genes.predictors" specified by "--extract" is the file arising from the first step. And then, it reported the following error:

Error, the predictor filterings ("--extract", "--exclude" or "--chr") provided now were not used with "--cut-genes"

Do you have any thoughts on fixing it? Thanks.

**Comment by takiy-berrandou** [comment]
Hi
Concerning the command line used for step 2, from the error message it indicates that you need to use "--extract" argument with the list of SNPs to be extracted in the first step when using --cut-genes. then you can use --extract in the step 2 command line. because LDAK is using files generated in step 1.

I guess you want to limit analysis to SNPs included in genes window only, so the strategy could be running --cut-genes a first time to generate genes.predictors then run second time --cut-genes + --extract genes.predictors then --calc-genes-reml + --extract genes.predictors.

**Comment by zqsha** [comment]
Hi,
Thanks for your reply. Yes, I wanted to limit the analysis SNPs included in genes window only. If I did not use "--extract" in the first step and second step, then it will show the following error:
Error, test.txt contains summary statistics for only 5696981 of the 7186768 predictors; either correct the file or use "--extract" or "--exclude" to exclude predictors without summary statistics.
That's why I try to avoid this error by specifying the "--extract" function.

Thanks.

**Comment by takiy-berrandou** [comment]
ok, I see here the issue is your summary statistics does not cover all SNPs in the bfile of reference panel.
What I suggest to avoid this error is to use --extract with common list of SNPs between the summary statistics and the reference panel in both steps 1 and 2. 
the common list of SNPs can be obtained from the intersect of .bim file SNPs column and the SNPs in summary statistics file (test.txt). for example in R by using intersect() then writing these SNPs ids into a text file.

**Comment by zqsha** [comment]
OK. Thanks. I just now used "intersect" function to output the overlapping SNPs between the variants in summary statistics and reference panel, i.e. **6,695,476** SNPs, which were saved in "asd_snp.txt". And then I run the analysis using the following command lines:
step1: Divide predictors into genes:
./ldak5.2.linux
--cut-genes asd
--genefile GRCh37_ensembl_GENES.loc
--gene-buffer 50000
--bfile g1000_nonFin_eur_imp_chr_1_22_posid_common_snps
--extract asd_snp.txt

step2: Test each gene for association
./ldak5.2.linux
--calc-genes-reml asd
--summary test.txt
--bfile g1000_nonFin_eur_imp_chr_1_22_posid_common_snps
--ignore-weights YES
--power -0.25
--extract asd_snp.txt

But, it reported the following error:
Error, test.txt contains summary statistics for only **5696981** of the 7186768 predictors; either correct the file or use "--extract" or "--exclude" to exclude predictors without summary statistics.

We can see there are 6695476 overlapping SNPs examined by "intersect" function. However, it says only 5696981 SNPs are available. I think there should be 6695476 out of 7186768 available SNPs. Right?

**Comment by takiy-berrandou** [comment]
did you check for duplicated and multi-allelic SNPs? Also, if your variant IDs are Chr:Pos You should check for REF/ALT alleles too.
can you share a complete screen out log? to see clearly what causing the error.

**Comment by zqsha** [comment]
OK. Get it. I have excluded duplicated SNPs, But I think I also need to exclude the SNP with ambiguous alleles in GWAS summary statistics. Alternatively, I can specify "--allow-ambiguous" as "yes" if I confirm these SNPs. So, I just now tried to use the below command line:
step2: Test each gene for association
./ldak5.2.linux
--calc-genes-reml asd
--summary test.txt
--bfile g1000_nonFin_eur_imp_chr_1_22_posid_common_snps
--ignore-weights YES
--power -0.25
--extract asd_snp.txt
--allow-ambiguous YES

the third step: 
./ldak5.2.linux
--join-genes-reml asd

There is no error reported. But, when I check the p-values in the "prs.all.pvalues". I found almost all of the p-values for genes are identical, which seems incorrect, such as
1_KLHL17 7.1017e-01
2_AGRN 7.1017e-01
3_C1orf159 7.1017e-01
4_TNFRSF18 7.1017e-01
5_ACAP3 7.1017e-01
6_PUSL1 7.1017e-01
7_ATAD3B 7.1017e-01
8_ATAD3A 7.1017e-01
9_TMEM240 7.1017e-01
10_MMP23B 0.0000e+00
11_NADK 7.1017e-01
12_TMEM52 7.1017e-01
13_GABRD 7.1017e-01
14_PRKCZ 7.1017e-01

Below is output on the screen:
Performing gene/chunk-based REML for Partition 1 (out of 1)

Predictors will be centred then scaled by V^(-0.2500/2) (option "--power"), where V=2*MAF*(1-MAF), the expected variance assuming Hardy-Weinberg Equilibrium; to instead scale based on observed variance use "--hwe-stand NO"

Will analyse the observed phenotype and 10 permutations (to change this number use "--gene-permutations")

Will thin each gene/chunk so that there are no pairs of predictors with correlation squared greater than 0.5000 (to change this threshold use "--gene-prune")

Will exclude genes whose estimated heritability is more than 10.0000 times the estimate from least-squares regression (to change this threshold use "--her-limit")

You can use "--shrink" to scale values of each gene/chunk correlation matrix

If you would like to randomly shuffle the phenotypes, add "--permute YES"

The random number generators, used when permuting the phenotype, have been seeded randomly; to instead specify the value, use "--random-seed"

To run the parallel version of LDAK, use "--max-threads" (this will only reduce runtime for some commands)

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

Reading IDs for 404 samples from g1000_nonFin_eur_imp_chr_1_22_posid_common_snps.fam

Reading details for 7186768 predictors from g1000_nonFin_eur_imp_chr_1_22_posid_common_snps.bim

Reading list of 6695476 predictors to extract from asd_snp.txt

Reading list of 6695476 predictors used with "--cut-genes" from genes.predictors

Data contain 404 samples and 7186768 predictors; will be using 404 and 6695476

Reading summary statistics from asd_orig.txt
In total, 998495 predictors have ambiguous alleles

Have found summary statistics for all 6695476 predictors
First few stats and ns are: 1:752566 2759.473 46350.0 | 1:752721 2821.970 46350.0 | 1:754182 2315.718 46350.0

The longest gene/chunk contains 14185 predictors

Warning, to perform the analysis will require approximately 3.0 Gb

Performing REML for Gene/Chunk 1 of 3639 in Partition 1
Performing REML for Gene/Chunk 201 of 3639 in Partition 1
Performing REML for Gene/Chunk 401 of 3639 in Partition 1
Performing REML for Gene/Chunk 601 of 3639 in Partition 1
Performing REML for Gene/Chunk 801 of 3639 in Partition 1
Performing REML for Gene/Chunk 1001 of 3639 in Partition 1
Performing REML for Gene/Chunk 1201 of 3639 in Partition 1
Performing REML for Gene/Chunk 1401 of 3639 in Partition 1
Performing REML for Gene/Chunk 1601 of 3639 in Partition 1
Performing REML for Gene/Chunk 1801 of 3639 in Partition 1
Performing REML for Gene/Chunk 2001 of 3639 in Partition 1
Performing REML for Gene/Chunk 2201 of 3639 in Partition 1
Performing REML for Gene/Chunk 2401 of 3639 in Partition 1
Performing REML for Gene/Chunk 2601 of 3639 in Partition 1
Performing REML for Gene/Chunk 2801 of 3639 in Partition 1
Performing REML for Gene/Chunk 3001 of 3639 in Partition 1
Performing REML for Gene/Chunk 3201 of 3639 in Partition 1
Performing REML for Gene/Chunk 3401 of 3639 in Partition 1
Performing REML for Gene/Chunk 3601 of 3639 in Partition 1

REML estimates saved in remls.1

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
Mission completed. All your basepair are belong to us :)
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
zhisha@lux13:~> ./ldak5.2.linux \
> --join-genes-reml asd
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
LDAK - Software for obtaining Linkage Disequilibrium Adjusted Kinships and Loads More
Version 5.2 - Help pages at http://www.ldak.org
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

There is one pair of arguments:
--join-genes-reml asd

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

Joining results from gene/chunk-based REML across 1 partition

To run the parallel version of LDAK, use "--max-threads" (this will only reduce runtime for some commands)

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

Joined results saved in remls.all (Column 12 contains p-values based on 10 permutations), with details of the assumed null distribution saved in gammas, and maximums in maximums

To clump results, use "--thin-tops" with "--sp prs.all", "--pvalues prs.all.pvalues" and "--SNP-data NO" (you should also use "--cutoff", "--window-prune" and "--window-kb" to specify clumping parameters)

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
Mission completed. All your basepair are belong to us :)
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

**Comment by takiy-berrandou** [comment]
Hi 
Thanks for sharing the screen out log. for completeness it would be great to share all of them including the one from "--cut-genes".

Answers and  comments:
Yes, when we are sure about REF/ALT alleles in our summary statistics we can include the ambiguous variants (A/T and G/C) into the analysis with " --allow-ambiguous YES".

From the log two points are bothering me, 
The first point: I see that you have only 3639 annotated genes when we expect something superior to17000 genes given the number of SNPs included in the summary statistics (6695476 SNPs, imputed data I guess). Can you share the screen out log from Step1 to investigate.

The second point, from "First few stats and ns are: 1:752566 2759.473 46350.0 | 1:752721 2821.970 46350.0 | 1:754182 2315.718 46350.0". I notice that you have large chisq stat for variants e.g., 2759.473, 2821.970, 2315.718 are too large. for example from the PGC summary stat of ASD used in the paper we have 1:752566 0.145 44368.0 | 1:752721 0.045 44368.0 | 1:754182 0.250 44368.0. For recall, LDAK-GBAT use Chi_Stat (Z_Stat^2) as input. This point may explain the final pvalues result you obtain.

Final small precision, final results can be found in remls.all file which is more detailed. prs.all.pvalues is used for the clumping purpose only.

Best

**Comment by zqsha** [comment]
Hi, 
Thanks for your reply. I agree that the statistics of SNPs could lead to the final results. I used autism GWAS summary statistics from this study (https://www.nature.com/articles/s41588-019-0344-8). This study mentioned they included 18,381 individuals with ASD and 27,969 controls, with a total of 46350 subjects.
After downloading GWAS summary statistics, I found this GWAS summary statistics include the following information.
CHR	SNP	BP	A1	A2	INFO	OR	SE	P
8	rs62513865	101592213	T	C	0.949	1.00652	0.027	0.8086
8	rs79643588	106973048	A	G	0.997	1.01786	0.024	0.4606
8	rs17396518	108690829	T	G	0.987	0.96127	0.014	0.004647
8	rs983166	108681675	A	C	0.998	0.97990	0.0139	0.1452
8	rs28842593	103044620	T	C	0.857	0.99591	0.0203	0.8415
8	rs35107696	109712249	A	AT	0.999	1.01308	0.0165	0.4302

Based on the principles of summary statistics mentioned in LDAK-GBAT, I calculated a Gaussian test statistic for each SNP, that is, Z=E/S, where E represents the estimate of effect size (or log odds) of a predictor, and S is its standard deviation. So, does it make sense to calculate E/S by log(OR)/SE?

Thanks.

**Comment by zqsha** [comment]
Another request for your suggestion. As you know, we often need to set the gene window size for gene-based analysis in MAGMA. But, in the LDAK-GBAT, by default, LDAK will only consider predictors inside genes. Based on the algorithm of LDAK used for gene-based calculations, do you recommend the users set the size of the gene window? Thanks so much.

**Comment by takiy-berrandou** [comment]
Thanks for the additional details.
in our paper we used the same GWAS summary statistics for autism (from PGC). However, given the trait is binary and Ncases!=Nctrls we suggest to use Neff=4/(1/Ncases+1/Nctrls) to match N when trait is continuous and this explain the "44368" in my example.
I agree Z=log(OR)/SE but as mentioned in previous reply LDAK-GBAT require a direction and Chi_STAT=Z^2 if I use previous equation Chi_Stat =(log(OR)/SE)^2. 
taking the values from sample table in your message Chi_Stat values should be  0.010927287, 0.102614719, 1.501432077, 0.402470875, 0.007687807, 0.116994749 respectively.

Concerning, the gene window. in LDAK-GBAT we can set a larger window for genes by using "--gene-buffer <integer>, --up-buffer <integer> or --down-buffer <integer>" for details see https://dougspeed.com/gene-based-analysis/
or alternatively customize the annotation file by changing START/END position to include extra region.
The main motivation when changing the gene window is to include gene expression regulation region, however this need a better knowledge about their location ad I don't think adding same buffer for all genes is a good startegy because those regulation region might have different distance from genes and might be shared by different genes as well. So keeping a standard gene definition is simple and avoid adding supplemental assumption.
otherwise, one can analyse all regions by using a chunk definition instead of using gene-based definition. for details see --chunks in https://dougspeed.com/gene-based-analysis/.

**Comment by zqsha** [comment]
OK, great, thanks. After I rerunning this, I found some genes have the same p-values in the "prs.all.pvalues" file (e.g. 7.0872e-01), although not all of the genes have this p-value. There is no error reported.
1_KLHL17 1.2798e-01
2_AGRN 2.1129e-01
3_C1orf159 7.0872e-01
4_TNFRSF18 7.0872e-01
5_ACAP3 7.0872e-01
6_PUSL1 7.0872e-01
7_ATAD3B 7.0872e-01
8_ATAD3A 7.0872e-01
9_TMEM240 3.3958e-01
10_MMP23B 7.0872e-01
11_NADK 7.0872e-01
12_TMEM52 3.7909e-01
13_GABRD 8.0823e-02
14_PRKCZ 7.0872e-01
15_MORN1 8.0183e-02
16_PLCH2 3.1960e-02
17_PANK4 4.5415e-02
18_TNFRSF14 5.0160e-02
19_CEP104 7.0872e-01
20_DFFB 7.0872e-01
21_AJAP1 7.0872e-01
22_NPHP4 6.6856e-02
23_CHD5 7.0872e-01
24_RNF207 3.6838e-01
25_GPR153 7.0872e-01
26_TNFRSF25 7.0872e-01
27_PLEKHG5 7.0872e-01
28_NOL9 3.3298e-01
29_ZBTB48 1.7481e-01
30_NMNAT1 7.0872e-01
31_FBXO44 7.0872e-01
32_FBXO6 7.0872e-01
33_MAD2L2 2.6030e-01
34_NPPA 7.0872e-01
35_VPS13D 7.0872e-01
36_LRRC38 7.0872e-01
37_PDPN 2.1265e-01
38_EFHD2 7.0872e-01
39_AGMAT 1.7540e-01
40_SLC25A34 7.0872e-01
41_PADI4 1.3497e-01
42_IGSF21 1.0360e-01
Is it normal? Is it because these p-values were obtained by permutation tests?

Here are the results reported in the "remls.all" file,
Gene_Name Gene_Chr Gene_Start Gene_End Length Heritability SD Null_Likelihood Alt_Likelihood LRT_Stat LRT_P_Raw LRT_P_Perm Her_Liability SD_Liability
1_KLHL17 1 895968 901099 14 0.000066 0.000001 -65175.9174 -65175.4385 0.9578 1.6387e-01 1.2798e-01 NA NA
2_AGRN 1 955504 991499 20 0.000046 0.000001 -65175.9174 -65175.7188 0.3972 2.6426e-01 2.1129e-01 NA NA
3_C1orf159 1 1017199 1051736 15 0.000001 NA -65175.9174 -65175.9174 0.0000 7.5000e-01 7.0872e-01 NA NA
4_TNFRSF18 1 1138889 1142163 21 0.000001 NA -65175.9174 -65175.9174 0.0000 7.5000e-01 7.0872e-01 NA NA
5_ACAP3 1 1227765 1243304 27 0.000001 NA -65175.9174 -65175.9174 0.0000 7.5000e-01 7.0872e-01 NA NA
6_PUSL1 1 1243963 1247057 21 0.000001 NA -65175.9174 -65175.9174 0.0000 7.5000e-01 7.0872e-01 NA NA
7_ATAD3B 1 1407140 1444852 27 0.000001 NA -65175.9174 -65175.9174 0.0000 7.5000e-01 7.0872e-01 NA NA
8_ATAD3A 1 1447524 1470067 15 0.000001 NA -65175.9174 -65175.9174 0.0000 7.5000e-01 7.0872e-01 NA NA
9_TMEM240 1 1470159 1475740 14 0.000016 0.000001 -65175.9174 -65175.8938 0.0472 4.1399e-01 3.3958e-01 NA NA
10_MMP23B 1 1567061 1570030 3 0.000001 NA -65175.9174 -65175.9174 0.0000 7.5000e-01 7.0872e-01 NA NA
11_NADK 1 1682672 1711508 14 0.000001 NA -65175.9174 -65175.9174 0.0000 7.5000e-01 7.0872e-01 NA NA
12_TMEM52 1 1849030 1850740 17 0.000010 0.000001 -65175.9174 -65175.9120 0.0108 4.5870e-01 3.7909e-01 NA NA
13_GABRD 1 1950769 1962192 29 0.000155 0.000002 -65175.9174 -65175.1361 1.5626 1.0564e-01 8.0823e-02 NA NA
14_PRKCZ 1 1981910 2116834 63 0.000001 NA -65175.9174 -65175.9174 0.0000 7.5000e-01 7.0872e-01 NA NA
15_MORN1 1 2251720 2323190 83 0.000252 0.000002 -65175.9174 -65175.1306 1.5736 1.0484e-01 8.0183e-02 NA NA

Below are the command lines that I used.
step1: Divide predictors into genes:
./ldak5.2.linux
--cut-genes asd
--genefile GRCh37_ensembl_GENES.loc
--gene-buffer 50000
--bfile g1000_nonFin_eur_imp_chr_1_22_posid_common_snps
--extract asd_snp.txt

step2: Test each gene for association
./ldak5.2.linux
--calc-genes-reml asd
--summary test.txt
--bfile g1000_nonFin_eur_imp_chr_1_22_posid_common_snps
--ignore-weights YES
--power -0.25
--allow-ambiguous YES
--extract asd_snp.txt

step3:  Join results across genes
./ldak5.2.linux
--join-genes-reml asd

Thanks.

**Comment by takiy-berrandou** [comment]
Thanks for this.
from remls.all you notice that pvalues reported in prs.all.pvalues  are from LRT_P_Perm column. 
All pvalues are obtained from permutation procedure (explained in the paper). 
concerning pvalues == 7.0872e-01 (LRT_P_Perm) or == 7.5000e-01 (LRT_P_Raw), those values are set by default for non significant genes were estimation of heritability SD could not be done (SD==NA) and therefore the gene P-value is non significant.
Best

**Comment by zqsha** [comment]
OK. Great. That makes sense now. Thanks for clearing it up. I really appreciate it.
